export const API_BASE_URL = "https://api.openweathermap.org/data/2.5/weather";
export const API_KEY = "4817d95667154e2b474184f60dbbec68";
export const statePopulationData = [
  { name: "Uttar Pradesh", code: "UP", population: 224979000, temperature: 22 },
  { name: "Bihar", code: "BR", population: 124799926, temperature: 30 },
  { name: "Madhya Pradesh", code: "MP", population: 85358965, temperature: 44 },
  { name: "West Bengal", code: "WB", population: 99609303, temperature: 42 },
  {
    name: "Himachal Pradesh",
    code: "HP",
    population: 7451955,
    temperature: 43,
  },
  { name: "Punjab", code: "PB", population: 30141373, temperature: 28 },
  { name: "Haryana", code: "HR", population: 28204692, temperature: 15 },
  { name: "Rajasthan", code: "RJ", population: 81032689, temperature: 17 },
  { name: "Maharashtra", code: "MH", population: 123144223, temperature: 48 },
  { name: "Andhra Pradesh", code: "AP", population: 53903393, temperature: 19 },
  { name: "Gujarat", code: "GJ", population: 63872399, temperature: 33 },
  { name: "Delhi", code: "DL", population: 19814000, temperature: 37 },
  { name: "Jharkhand", code: "JH", population: 38593948, temperature: 48 },
  { name: "Tamil Nadu", code: "TN", population: 77841267, temperature: 49 },
  { name: "Uttarakhand", code: "UK", population: 11141048, temperature: 23 },
];

export const citiesData = [
  {
    cityName: "Visakhapatnam",
    temperature: 15,
    population: 2035922,
    stateCode: "AP",
  },
  {
    cityName: "Vijayawada",
    temperature: 4,
    population: 1498919,
    stateCode: "AP",
  },
  {
    cityName: "Guntur",
    temperature: 25,
    population: 748685,
    stateCode: "AP",
  },
  {
    cityName: "Nellore",
    temperature: 28,
    population: 606409,
    stateCode: "AP",
  },
  {
    cityName: "Kurnool",
    temperature: 40,
    population: 484327,
    stateCode: "AP",
  },
  {
    cityName: "Patna",
    temperature: 50,
    population: 18700000,
    stateCode: "BR",
  },
  {
    cityName: "Gaya",
    temperature: 29,
    population: 11690000,
    stateCode: "BR",
  },
  {
    cityName: "Bhagalpur",
    temperature: 16,
    population: 2210000,
    stateCode: "BR",
  },
  {
    cityName: "Muzaffarpur",
    temperature: 12,
    population: 3520000,
    stateCode: "BR",
  },
  {
    cityName: "Darbhanga",
    temperature: 56,
    population: 4720000,
    stateCode: "BR",
  },
  {
    cityName: "Lucknow",
    temperature: 28,
    population: 28156000,
    stateCode: "UP",
  },
  {
    cityName: "Kanpur",
    temperature: 38,
    population: 27680000,
    stateCode: "UP",
  },
  {
    cityName: "Agra",
    temperature: 20,
    population: 28230000,
    stateCode: "UP",
  },
  {
    cityName: "Varanasi",
    temperature: 27,
    population: 22780000,
    stateCode: "UP",
  },
  {
    cityName: "Allahabad",
    temperature: 35,
    population: 25800000,
    stateCode: "UP",
  },
  {
    cityName: "Kolkata",
    temperature: 39,
    population: 4631392,
    stateCode: "WB",
  },
  {
    cityName: "Asansol",
    temperature: 15,
    population: 1392047,
    stateCode: "WB",
  },
  {
    cityName: "Siliguri",
    temperature: 27,
    population: 705579,
    stateCode: "WB",
  },
  {
    cityName: "Durgapur",
    temperature: 16,
    population: 566517,
    stateCode: "WB",
  },
  {
    cityName: "Bardhaman",
    temperature: 36,
    population: 347016,
    stateCode: "WB",
  },
  {
    cityName: "Faridabad",
    temperature: 50,
    population: 1404656,
    stateCode: "HR",
  },
  {
    cityName: "Gurugram",
    temperature: 12,
    population: 877110,
    stateCode: "HR",
  },
  {
    cityName: "Panipat",
    temperature: 25,
    population: 294150,
    stateCode: "HR",
  },
  {
    cityName: "Sonipat",
    temperature: 32,
    population: 278149,
    stateCode: "HR",
  },
  {
    cityName: "Karnal",
    temperature: 38,
    population: 286827,
    stateCode: "HR",
  },
  {
    cityName: "New Delhi",
    temperature: 19,
    population: 257803,
    stateCode: "DL",
  },
  {
    cityName: "North Delhi",
    temperature: 36,
    population: 883418,
    stateCode: "DL",
  },
  {
    cityName: "South Delhi",
    temperature: 40,
    population: 2731929,
    stateCode: "DL",
  },
  {
    cityName: "East Delhi",
    temperature: 31,
    population: 1709346,
    stateCode: "DL",
  },
  {
    cityName: "West Delhi",
    temperature: 22,
    population: 2543243,
    stateCode: "DL",
  },
  {
    cityName: "Ahmedabad",
    temperature: 33,
    population: 5570585,
    stateCode: "GJ",
  },
  {
    cityName: "Surat",
    temperature: 45,
    population: 4467797,
    stateCode: "GJ",
  },
  {
    cityName: "Vadodara",
    temperature: 41,
    population: 2065771,
    stateCode: "GJ",
  },
  {
    cityName: "Rajkot",
    temperature: 30,
    population: 1575758,
    stateCode: "GJ",
  },
  {
    cityName: "Bhavnagar",
    temperature: 25,
    population: 593768,
    stateCode: "GJ",
  },
  {
    cityName: "Shimla",
    temperature: 8,
    population: 169578,
    stateCode: "HP",
  },
  {
    cityName: "Mandi",
    temperature: 23,
    population: 100000,
    stateCode: "HP",
  },
  {
    cityName: "Dharamshala",
    temperature: 16,
    population: 52622,
    stateCode: "HP",
  },
  {
    cityName: "Solan",
    temperature: 28,
    population: 40210,
    stateCode: "HP",
  },
  {
    cityName: "Kullu",
    temperature: 16,
    population: 16717,
    stateCode: "HP",
  },
  {
    cityName: "Ludhiana",
    temperature: 29,
    population: 1590556,
    stateCode: "PB",
  },
  {
    cityName: "Amritsar",
    temperature: 38,
    population: 1132383,
    stateCode: "PB",
  },
  {
    cityName: "Jalandhar",
    temperature: 45,
    population: 873725,
    stateCode: "PB",
  },
  {
    cityName: "Patiala",
    temperature: 50,
    population: 606688,
    stateCode: "PB",
  },
  {
    cityName: "Bathinda",
    temperature: 30,
    population: 285813,
    stateCode: "PB",
  },
  {
    cityName: "Mumbai",
    temperature: 28,
    population: 12442373,
    stateCode: "MH",
  },
  {
    cityName: "Pune",
    temperature: 34,
    population: 3115431,
    stateCode: "MH",
  },
  {
    cityName: "Nagpur",
    temperature: 16,
    population: 2405665,
    stateCode: "MH",
  },
  {
    cityName: "Nashik",
    temperature: 29,
    population: 1486053,
    stateCode: "MH",
  },
  {
    cityName: "Aurangabad",
    temperature: 41,
    population: 1171330,
    stateCode: "MH",
  },
  {
    cityName: "Indore",
    temperature: 33,
    population: 3272345,
    stateCode: "MP",
  },
  {
    cityName: "Bhopal",
    temperature: 25,
    population: 1883381,
    stateCode: "MP",
  },
  {
    cityName: "Jabalpur",
    temperature: 19,
    population: 1463067,
    stateCode: "MP",
  },
  {
    cityName: "Gwalior",
    temperature: 11,
    population: 1101981,
    stateCode: "MP",
  },
  {
    cityName: "Ujjain",
    temperature: 40,
    population: 515215,
    stateCode: "MP",
  },
  {
    cityName: "Jaipur",
    temperature: 50,
    population: 3073350,
    stateCode: "RJ",
  },
  {
    cityName: "Jodhpur",
    temperature: 40,
    population: 1137910,
    stateCode: "RJ",
  },
  {
    cityName: "Kota",
    temperature: 30,
    population: 1001694,
    stateCode: "RJ",
  },
  {
    cityName: "Bikaner",
    temperature: 42,
    population: 647804,
    stateCode: "RJ",
  },
  {
    cityName: "Ajmer",
    temperature: 22,
    population: 542321,
    stateCode: "RJ",
  },
  {
    cityName: "Ranchi",
    temperature: 36,
    population: 1150140,
    stateCode: "JH",
  },
  {
    cityName: "Jamshedpur",
    temperature: 35,
    population: 1132332,
    stateCode: "JH",
  },
  {
    cityName: "Dhanbad",
    temperature: 50,
    population: 1133225,
    stateCode: "JH",
  },
  {
    cityName: "Bokaro Steel City",
    temperature: 55,
    population: 563417,
    stateCode: "JH",
  },
  {
    cityName: "Hazaribagh",
    temperature: 33,
    population: 153599,
    stateCode: "JH",
  },

  {
    cityName: "Dehradun",
    temperature: 16,
    population: 714223,
    stateCode: "UK",
  },
  {
    cityName: "Haridwar",
    temperature: 22,
    population: 228832,
    stateCode: "UK",
  },
  {
    cityName: "Roorkee",
    temperature: 11,
    population: 114275,
    stateCode: "UK",
  },
  {
    cityName: "Haldwani",
    temperature: 26,
    population: 156078,
    stateCode: "UK",
  },
  {
    cityName: "Rudrapur",
    temperature: 36,
    population: 140857,
    stateCode: "UK",
  },
  {
    cityName: "Chennai",
    temperature: 36,
    population: 4681087,
    stateCode: "TN",
  },
  {
    cityName: "Coimbatore",
    temperature: 46,
    population: 1648928,
    stateCode: "TN",
  },
  {
    cityName: "Madurai",
    temperature: 26,
    population: 1231664,
    stateCode: "TN",
  },
  {
    cityName: "Tiruchirappalli",
    temperature: 16,
    population: 916857,
    stateCode: "TN",
  },
  {
    cityName: "Salem",
    temperature: 35,
    population: 919696,
    stateCode: "TN",
  },
];
